Fix undefined reference to `makedev`
Building `factc` with glibc2.26+ results in an undefined reference to `makedev` in `unix_stubs.c` due to makedev being moved to `sys/sysmacros.h` from `sys/types.h` for non-Apple/BSD systems. Using the 0.11.3 version of the core library instead of 0.11.2 fixes the issue.